name: colamd
version: 0.1.0
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Column approximate minimum degree ordering algorithm.
homepage: http://www.cise.ufl.edu/research/sparse/colamd/
dependencies:
  unittest: '>=0.11.0+3 <0.12.0'
